@echo off
setlocal enabledelayedexpansion

echo ===================================================
echo YT Smart Downloader Pro - Native Host Registration
echo ===================================================
echo.

:: Detect current directory
set "CURRENT_DIR=%~dp0"
:: Remove trailing backslash
set "CURRENT_DIR=%CURRENT_DIR:~0,-1%"
set "APP_JSON_PATH=%CURRENT_DIR%\native-app\app.json"
set "PROXY_PY_PATH=%CURRENT_DIR%\native-app\yt_proxy.py"

:: Escape backslashes for JSON format
set "ESCAPED_DIR=!CURRENT_DIR:\=\\!"
set "ESCAPED_PROXY=!PROXY_PY_PATH:\=\\!"

:: Check if python is available
where python.exe >nul 2>nul
if %errorlevel% neq 0 (
    echo [ERROR] Python is not installed or not in PATH!
    echo Please install Python and make sure to check "Add Python to PATH" during installation.
    pause
    exit /b 1
)

:: Find python path
for /f "tokens=*" %%i in ('where python.exe') do (
    set "PYTHON_PATH=%%i"
    goto :found_python
)
:found_python

set "ESCAPED_PYTHON=!PYTHON_PATH:\=\\!"

echo Found Python at: %PYTHON_PATH%
echo Current Directory: %CURRENT_DIR%
echo.

:: Create dynamic app.json using PowerShell to correctly handle JSON formatting
powershell -Command "$json = @{ name = 'com.yt.downloader'; description = 'YT Downloader Backend Proxy'; path = '%PYTHON_PATH%'; args = @('-u', '%PROXY_PY_PATH%'); type = 'stdio'; allowed_origins = @('chrome-extension://onpdgoacjbdnpacfgaddgbhpkefbplle/', 'extension://onpdgoacjbdnpacfgaddgbhpkefbplle/', 'chrome-extension://gideepikgphlpecnogcolgoacedhicia/', 'extension://gideepikgphlpecnogcolgoacedhicia/') }; $json | ConvertTo-Json -Depth 4 | Out-File -FilePath '%APP_JSON_PATH%' -Encoding ascii"

if %errorlevel% neq 0 (
    echo [ERROR] Failed to update native-app/app.json!
    pause
    exit /b 1
)
echo Updated native-app/app.json successfully.

:: Add registry keys for Chrome and Edge
echo Registering Native Messaging Host in Windows Registry...

:: Escape path for reg command
set "REG_PATH=!APP_JSON_PATH!"

reg add "HKCU\Software\Google\Chrome\NativeMessagingHosts\com.yt.downloader" /ve /d "!REG_PATH!" /f >nul
if %errorlevel% neq 0 (
    echo [ERROR] Failed to register registry key for Google Chrome!
    pause
    exit /b 1
)

reg add "HKCU\Software\Microsoft\Edge\NativeMessagingHosts\com.yt.downloader" /ve /d "!REG_PATH!" /f >nul
if %errorlevel% neq 0 (
    echo [ERROR] Failed to register registry key for Microsoft Edge!
    pause
    exit /b 1
)

echo.
echo ===================================================
echo [SUCCESS] Native Host registered successfully!
echo ===================================================
echo.
echo Next steps:
echo 1. Open Google Chrome or Microsoft Edge.
echo 2. Go to Extensions -> Developer Mode -> Load Unpacked.
echo 3. Select the folder: %CURRENT_DIR%
echo 4. Note the Extension ID generated by Chrome.
echo 5. If the Extension ID is different from "onpdgoacjbdnpacfgaddgbhpkefbplle",
echo    open 'native-app/app.json' and add your Extension ID to the 'allowed_origins' list.
echo.
pause
